version: "3"

services:
  openldap:
    image: "osixia/openldap"
    restart: always
    volumes:
      - openldap-ldap-volume:/var/lib/ldap
      - openldap-slapd.d-volume:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${OPENLDAP_ORGANISATION}
      - LDAP_DOMAIN=${OPENLDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${OPENLDAP_ADMIN_PASSWORD}

  gitlab:
    image: "gitlab/gitlab-ce"
    restart: always
    ports: 
      - "80:80"
      - "5443:443"
      - "522:22"
    volumes:
      - gitlab-etc-volume:/etc/gitlab
      - gitlab-opt-volume:/var/opt/gitlab
      - gitlab-log-volume:/var/log/gitlab
  
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins-home-volume:/var/jenkins_home

  ftp-releases:
    image: ftp-server:latest
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/releases:/usr/share/nginx/html/releases
    ports:
      - "521:21"
      - "580:80"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=localhost

volumes:
  openldap-ldap-volume:
  openldap-slapd.d-volume:
  gitlab-etc-volume:
  gitlab-opt-volume:
  gitlab-log-volume:
  jenkins-home-volume:
  phpldapadmin-volume:
