version: "3"

services:

  ldap-admin:
    image: "osixia/phpldapadmin"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    volumes:
      - phpldapadmin-volume:/var/www/phpldapadmin